import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-50 px-4 py-16 dark:bg-slate-950 sm:px-6 lg:px-8">
      <div className="mx-auto w-full max-w-3xl rounded-3xl border border-slate-200 bg-white p-8 dark:border-slate-800 dark:bg-slate-900">
        <h1 className="text-3xl font-black text-slate-900 dark:text-slate-100">Privacy Policy</h1>
        <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Last updated: September 20, 2026</p>

        <p className="mt-6 text-sm leading-7 text-slate-600 dark:text-slate-300">
          For You Newsletter ("we," "us," or "our") operates the For You Newsletter service
          accessible at foryounewsletter.com (the "Service"). This Privacy Policy explains
          what information we collect, how we use it, and your rights regarding that
          information.
        </p>

        <div className="mt-6 rounded-2xl border border-sky-200 bg-sky-50 p-5 dark:border-sky-900/50 dark:bg-sky-950/30">
          <h2 className="text-base font-bold text-sky-900 dark:text-sky-200">
            Artificial Intelligence (AI) Disclosure
          </h2>
          <p className="mt-2 text-sm leading-7 text-slate-700 dark:text-slate-300">
            Your newsletter content is generated by automated artificial intelligence. We
            use a large language model (currently OpenAI's GPT models) to summarize and
            rewrite news drawn from third-party sources into the sections you select. In
            plain terms:
          </p>
          <ul className="mt-3 list-disc pl-5 text-sm leading-7 text-slate-700 dark:text-slate-300 space-y-1">
            <li>
              <strong>Content is AI-generated, not written by human editors.</strong> AI can
              make mistakes, misstate facts, or omit context. Treat every item as a starting
              point and verify anything you rely on against the original source we link.
            </li>
            <li>
              <strong>What we send to the AI provider:</strong> your selected topics and
              customization details, plus article text from public sources — enough for the
              model to write your sections. We do not send your password, payment details, or
              browsing history.
            </li>
            <li>
              <strong>We do not use your data to train AI models,</strong> and our AI provider
              does not train its models on data sent through our API integration.
            </li>
            <li>
              AI is used to generate newsletter content only. It does not make decisions about
              your account, billing, eligibility, or any other consequential matter.
            </li>
          </ul>
        </div>

        <Section title="1. Information We Collect">
          <Subsection title="Account information">
            When you create an account, we collect your email address and any display name
            you provide. This is used to authenticate you and deliver your newsletter.
          </Subsection>
          <Subsection title="Newsletter preferences">
            We store the topics, subtopics, and customization settings you choose so we can
            generate a newsletter personalized to you.
          </Subsection>
          <Subsection title="Payment information">
            Payments are processed entirely by Stripe, Inc. We never see or store your card
            number, bank details, or full payment credentials. We receive a Stripe customer
            ID and subscription status from Stripe solely to manage your plan.
          </Subsection>
          <Subsection title="Usage and analytics data">
            If you accept analytics cookies, we collect product-usage events through PostHog,
            including page views, feature use, autocapture, and session recording. Your
            PostHog distinct ID is your account UUID (Linked to you: Yes). You can Reject
            analytics in the cookie banner, and we honor Do Not Track as a rejection. Crash
            reports via Sentry are necessary to run the Service and are not consent-gated.
          </Subsection>
          <Subsection title="Technical data">
            Standard server and infrastructure logs may record your IP address, browser type,
            and request timestamps. These are used for security, debugging, and abuse
            prevention, and are not linked to your account for marketing purposes.
          </Subsection>
        </Section>

        <Section title="Privacy Nutrition Label">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            An at-a-glance summary of the data we collect, why, and whether it is linked to
            your identity. Product analytics are <strong>Linked to you: Yes</strong> because
            PostHog uses your account UUID. This mirrors the format used by app stores. The sections below
            provide the full detail.
          </p>
          <div className="mt-4 overflow-x-auto">
            <table className="w-full border-collapse text-left text-sm">
              <thead>
                <tr className="border-b border-slate-200 dark:border-slate-700">
                  <th className="py-2 pr-4 font-bold text-slate-700 dark:text-slate-200">Data type</th>
                  <th className="py-2 pr-4 font-bold text-slate-700 dark:text-slate-200">Purpose</th>
                  <th className="py-2 pr-4 font-bold text-slate-700 dark:text-slate-200">Linked to you</th>
                  <th className="py-2 font-bold text-slate-700 dark:text-slate-200">Used to track you</th>
                </tr>
              </thead>
              <tbody className="text-slate-600 dark:text-slate-300">
                {[
                  ["Email address", "Account, login, newsletter delivery", "Yes", "No"],
                  ["Newsletter preferences", "Personalizing your content", "Yes", "No"],
                  ["Payment/subscription status", "Billing (card data held by Stripe, not us)", "Yes", "No"],
                  ["Usage & analytics events", "Improving the product (PostHog UUID, autocapture, session recording)", "Yes", "Yes"],
                  ["Crash reports (Sentry)", "Error monitoring and reliability", "Yes", "No"],
                  ["Technical logs (IP, browser)", "Security, debugging, abuse prevention", "Not for marketing", "No"],
                ].map((row) => (
                  <tr key={row[0]} className="border-b border-slate-100 dark:border-slate-800">
                    <td className="py-2 pr-4 font-semibold">{row[0]}</td>
                    <td className="py-2 pr-4">{row[1]}</td>
                    <td className="py-2 pr-4">{row[2]}</td>
                    <td className="py-2">{row[3]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
            We do not sell your personal information, and we do not use it for cross-context
            behavioral advertising or third-party tracking. We do not offer file uploads.
          </p>
        </Section>

        <Section title="Email open and click tracking">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            Newsletter emails may include an open pixel and click redirects signed with HMAC
            so we can tell whether an issue was opened or a source link was followed. These
            are first-party metrics. We do not use a third-party ad network for this.
          </p>
        </Section>

        <Section title="Sponsored content">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            Free and Plus plans may include sponsored content selected from your chosen
            topics. We do not sell your personal data to advertisers. Premium never includes
            sponsored content. At launch there may be no live campaigns — the slot stays empty
            until we run one.
          </p>
        </Section>

        <Section title="Trials, billing, and cancellation">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            New Plus or Premium subscribers who have never used a trial receive a 7-day free
            trial. Unless you cancel, your card is charged $4.99 (Plus) or $9.99 (Premium)
            when the trial ends. We send a reminder 48–72 hours before that charge. Canceling
            a paid plan takes effect at period end; your account and data stay until you
            delete them. Cancel from Settings or Stripe&apos;s customer portal — both are
            valid.
          </p>
        </Section>

        <Section title="2. How We Use Your Information">
          <ul className="mt-2 list-disc pl-5 text-sm leading-7 text-slate-600 dark:text-slate-300 space-y-1">
            <li>To generate and deliver your personalized newsletter by email and in-app.</li>
            <li>To process subscription payments and manage your plan.</li>
            <li>To authenticate you and keep your account secure.</li>
            <li>To improve the Service based on aggregated, anonymized usage patterns.</li>
            <li>
              To send transactional emails (e.g., account confirmations, billing receipts).
              We do not send promotional or marketing emails beyond the newsletter you
              explicitly signed up for. Every newsletter email includes an unsubscribe link.
            </li>
          </ul>
        </Section>

        <Section title="3. How We Share Your Information">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            We share data with the following service providers only to the extent necessary
            to operate the Service. We do not sell your personal information to third
            parties.
          </p>
          <ul className="mt-3 list-disc pl-5 text-sm leading-7 text-slate-600 dark:text-slate-300 space-y-2">
            <li>
              <strong>Supabase</strong> — authentication and database hosting. Your account
              data and newsletter preferences are stored in Supabase.
            </li>
            <li>
              <strong>Stripe</strong> — payment processing and subscription management.
              Stripe's own{" "}
              <a
                href="https://stripe.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-sky-600 hover:underline"
              >
                Privacy Policy
              </a>{" "}
              governs data handled during payment processing.
            </li>
            <li>
              <strong>Resend</strong> — transactional email delivery of your newsletter.
              Your email address is transmitted to Resend solely to send your newsletter and
              account emails.
            </li>
            <li>
              <strong>OpenAI</strong> — AI inference for newsletter generation. Your selected
              topic preferences and public source article text are sent to OpenAI to produce
              content summaries. Data sent through our API integration is not used to train
              OpenAI's models, and no persistent user profile is created with OpenAI on your
              behalf. See OpenAI's{" "}
              <a
                href="https://openai.com/policies/privacy-policy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-sky-600 hover:underline"
              >
                Privacy Policy
              </a>{" "}
              for details.
            </li>
            <li>
              <strong>Upstash (Redis)</strong> — rate limiting and short-lived request
              caching. No personally identifiable information is stored long-term in this
              layer.
            </li>
            <li>
              <strong>PostHog</strong> — product analytics when you accept cookies. We identify
              you by your account UUID, and may record sessions. See PostHog's{" "}
              <a
                href="https://posthog.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-sky-600 hover:underline"
              >
                Privacy Policy
              </a>{" "}
              for details.
            </li>
            <li>
              <strong>Sentry</strong> — crash reports, stack traces, and request context so we
              can fix outages. This is necessary error monitoring, not advertising, and is not
              gated by the cookie banner.
            </li>
            <li>
              <strong>Google OAuth</strong> — optional sign-in. Google provides your email (and
              name, if you share it) so we can create your account.
            </li>
            <li>
              <strong>WeatherAPI.com</strong> — city names you enter for weather sections.
            </li>
            <li>
              <strong>Finnhub</strong> — ticker symbols you select for stock quotes. We do not
              send your identity to Finnhub.
            </li>
            <li>
              <strong>NewsAPI</strong> — topic search terms used as a rescue source when RSS
              feeds are thin.
            </li>
          </ul>
          <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
            We may also disclose information if required by law, court order, or to protect
            the rights, property, or safety of For You Newsletter, our users, or the public.
          </p>
        </Section>

        <Section title="4. Data Security">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            We implement reasonable technical and organizational measures to protect your
            personal information against unauthorized access, loss, or misuse. All data
            transmitted between your browser and our Service is encrypted via HTTPS. Your
            account is protected by authentication managed through Supabase.
          </p>
          <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
            No method of transmission or storage is 100% secure. While we work to protect
            your data, we cannot guarantee absolute security. If you believe your account
            has been compromised, please contact us immediately.
          </p>
        </Section>

        <Section title="5. Data Retention">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            We retain your account data and newsletter preferences for as long as your
            account is active. If you delete your account, we will delete or anonymize your
            personal data within a reasonable period, except where we are required to retain
            records for legal or financial compliance purposes (e.g., Stripe transaction
            records required for tax and accounting purposes).
          </p>
        </Section>

        <Section title="6. Cookies and Tracking Technologies">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            We use cookies and similar browser storage technologies to keep you signed in
            and remember your preferences. For full details, see our{" "}
            <Link href="/cookies" className="text-sky-600 hover:underline">
              Cookie Policy
            </Link>
            .
          </p>
        </Section>

        <Section title="7. Third-Party Links">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            Your newsletter may contain links to third-party news articles and websites. We
            do not control those sites and are not responsible for their privacy practices
            or content. We encourage you to review the privacy policies of any third-party
            sites you visit.
          </p>
        </Section>

        <Section title="8. Your Privacy Rights">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            Depending on where you live, you may have the following rights regarding your
            personal information:
          </p>
          <ul className="mt-3 list-disc pl-5 text-sm leading-7 text-slate-600 dark:text-slate-300 space-y-1">
            <li>
              <strong>Access:</strong> Request a copy of the personal information we hold
              about you.
            </li>
            <li>
              <strong>Correction:</strong> Update inaccurate information. You can correct
              most information directly from your account dashboard.
            </li>
            <li>
              <strong>Deletion:</strong> Request that we delete your personal information,
              subject to legal retention obligations.
            </li>
            <li>
              <strong>Unsubscribe:</strong> Opt out of newsletter delivery at any time using
              the unsubscribe link in any newsletter email, or from your account settings.
            </li>
          </ul>
          <p className="mt-4 text-sm font-semibold text-slate-700 dark:text-slate-200">
            California Residents (CCPA/CPRA)
          </p>
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            If you are a California resident, you have the right to know what personal
            information we collect and how it is used, the right to delete your personal
            information, the right to correct inaccurate information, and the right to
            non-discrimination for exercising these rights. As stated above, we do not sell
            or share your personal information for cross-context behavioral advertising. To
            exercise any of these rights, contact us at the address below.
          </p>
          <p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">
            To exercise any privacy right, contact us at{" "}
            <a
              href="mailto:hello@foryounewsletter.com"
              className="text-sky-600 hover:underline"
            >
              hello@foryounewsletter.com
            </a>
            . We will respond within 45 days.
          </p>
        </Section>

        <Section title="9. Children">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            The Service is not directed to children under the age of 13, and we do not
            knowingly collect personal information from children under 13. If you believe
            a child under 13 has provided us with personal information, please contact us
            and we will promptly delete it.
          </p>
        </Section>

        <Section title="10. Changes to This Policy">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            We may update this Privacy Policy from time to time. When we do, we will revise
            the "Last updated" date at the top of this page. For material changes, we will
            make reasonable efforts to notify you (e.g., via email or a notice on the
            Service). Continued use of the Service after changes are posted constitutes
            your acceptance of the revised policy.
          </p>
        </Section>

        <Section title="11. Contact">
          <p className="mt-2 text-sm leading-7 text-slate-600 dark:text-slate-300">
            Questions or concerns about this Privacy Policy? Contact us at:{" "}
            <a
              href="mailto:hello@foryounewsletter.com"
              className="text-sky-600 hover:underline"
            >
              hello@foryounewsletter.com
            </a>
          </p>
        </Section>

        <Link
          href="/"
          className="mt-8 inline-block text-sm font-semibold text-sky-600 hover:underline"
        >
          Back to Home
        </Link>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-8">
      <h2 className="text-base font-bold text-slate-800 dark:text-slate-100">{title}</h2>
      {children}
    </div>
  );
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-3">
      <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-200">{title}</h3>
      <p className="mt-1 text-sm leading-7 text-slate-600 dark:text-slate-300">{children}</p>
    </div>
  );
}
